const BASE_URL_SITE = import.meta.env.VITE_REACT_APP_BACKEND_URL;
const API_KEY_PARAM = import.meta.env.VITE_API_KEY_PARAM
const BACKDROP_BASE_URL = import.meta.env.VITE_BACKDROP_BASE_URL
const BACKDROP_BASE_SMALL_URL = import.meta.env.VITE_BACKDROP_BASE_SMALL_URL
console.log("BASE_URL", API_KEY_PARAM)
export {BASE_URL_SITE, API_KEY_PARAM, BACKDROP_BASE_SMALL_URL, BACKDROP_BASE_URL};